CREATE DATABASE demo_db;
USE demo_db;
CREATE TABLE IF NOT EXISTS demo_table
(
  uid  INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  key1 VARCHAR(255) NOT NULL DEFAULT '',
  key2 VARCHAR(255) NOT NULL DEFAULT ''
);
